### ISSUE TITLE
CUDA out of memory in iCaRL strategy

### ISSUE THREAD

**Issue by lantao1234** [ContinualAI/avalanche#1075]
when i use the dataset with 10k or more images in the icarl strategy, i always  meet with the fault "CUDA out of memory".

When i check the official code of the iCaRL strategy, i found the "construct_exemplar_set" function will result in the "CUDA out of memory".  I think it may be  too risky to read all of the dataset and forward the model.feature_extractor. Anyone can help me? thu 

official code:

          class_patterns, _, _ = next(
               iter(DataLoader(cd.eval(), batch_size=len(cd)))
           )
           class_patterns = class_patterns.to(strategy.device)
           with torch.no_grad():
               mapped_prototypes = strategy.model.feature_extractor(
                   class_patterns
               ).detach()

**Comment by AntonioCarta** [comment]
You are right, `class_patterns` should be generated via small mini-batches to avoid OOM. It should be easy to fix if you want to try.

**Comment by AntonioCarta** [comment]
Fixed in #1167

**Comment by lantao1234** [comment]
> Fixed in #1167

Sorry, i still do not understand how to fix the OOM bug.  How can i use this fixed information? 
Thank you.

**Comment by AntonioCarta** [comment]
Are you using the master branch? it is sufficient to set a small enough `eval_batch_size`

**Comment by lantao1234** [comment]
ok, thank you very much.



---Original---
From: "Antonio ***@***.***&gt;
Date: Tue, Nov 8, 2022 21:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ContinualAI/avalanche] CUDA out of memory in iCaRL strategy (Issue #1075)




 
Are you using the master branch? it is sufficient to set a small enough eval_batch_size
