### ISSUE TITLE
checkpointing load gets stuck at evaluation after evaluating on experience 1

### ISSUE THREAD

**Issue by Melika-Ayoughi** [ContinualAI/avalanche#1286]
I'm running checkpointing on Icarl with cifar10. During training, the checkpoints are successfully saved. However, during evaluation, the code gets stuck at the second evaluation iteration.

**Here is the log before it gets stuck:**

Computing accuracy on the complete test set
-- >> Start of eval phase << --
-- Starting eval on experience 0 (Task 0) from test stream --
100%|█████████████████████████████████████████████| 5/5 [00:02<00:00,  2.22it/s]
> Eval on experience 0 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp000 = 376.8322
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp000 = 0
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp000 = 0.9880
	Loss_Exp/eval_phase/test_stream/Task000/Exp000 = 0.4751
	Time_Exp/eval_phase/test_stream/Task000/Exp000 = 2.2424
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp000 = 0.0120
-- Starting eval on experience 1 (Task 0) from test stream --
100%|█████████████████████████████████████████████| 5/5 [00:02<00:00,  2.38it/s]
> Eval on experience 1 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp001 = 396.1858
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp001 = 0
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp001 = 0.0670
	Loss_Exp/eval_phase/test_stream/Task000/Exp001 = 0.4746
	Time_Exp/eval_phase/test_stream/Task000/Exp001 = 2.0724
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp001 = 0.6570

**Here is my code to reproduce:**

reproduce(args.seed)
    RNGManager.set_random_seeds(args.seed)
    device = torch.device(
        f"cuda:{args.cuda}"
        if args.cuda >= 0 and torch.cuda.is_available()
        else "cpu"
    )
per_pixel_mean = get_dataset_per_pixel_mean(
            CIFAR10(
                expanduser("~") + "/.avalanche/data/cifar10/",
                train=True,
                download=True,
                transform=transforms.Compose([transforms.ToTensor()]),))

        transforms_group = dict(
            eval=(
                transforms.Compose(
                    [
                        transforms.ToTensor(),
                        lambda img_pattern: img_pattern - per_pixel_mean,
                    ]
                ),
                None,
            ),
            train=(
                transforms.Compose(
                    [
                        transforms.ToTensor(),
                        lambda img_pattern: img_pattern - per_pixel_mean,
                        icarl_cifar100_augment_data,
                    ]
                ),
                None,
            ),
        )

        train_set = CIFAR10(
            expanduser("~") + "/.avalanche/data/cifar10/",
            train=True,
            download=True,
        )
        test_set = CIFAR10(
            expanduser("~") + "/.avalanche/data/cifar10/",
            train=False,
            download=True,
        )

        train_set = AvalancheDataset(
            train_set,
            transform_groups=transforms_group,
            initial_transform_group="train",
        )
        test_set = AvalancheDataset(
            test_set,
            transform_groups=transforms_group,
            initial_transform_group="eval",
        )

        benchmark = nc_benchmark(
            train_dataset=train_set,
            test_dataset=test_set,
            n_experiences=10,
            task_labels=False,
            seed=args.seed,
            shuffle=True,  # todo
            fixed_class_order=args.fixed_class_order,
        )

checkpoint_plugin = CheckpointPlugin(FileSystemCheckpointStorage(directory=f'./output/checkpoints/{args.EXP_NAME}')
                                         , map_location=device)

evaluator = EvaluationPlugin(
        accuracy_metrics(minibatch=True, epoch=True, experience=True, stream=True),
        loss_metrics(minibatch=True, epoch=True, experience=True, stream=True),
        timing_metrics(epoch=True, epoch_running=True, experience=True, stream=True),
        forgetting_metrics(experience=True, stream=True),
        cpu_usage_metrics(experience=True),
        confusion_matrix_metrics(num_classes=benchmark.n_classes, save_image=True, stream=True),
        disk_usage_metrics(minibatch=True, epoch=True, experience=True, stream=True),
        # collect_all=True,
        loggers=[InteractiveLogger(),
                 TextLogger(open(f'./output/baseline/{args.EXP_NAME}/log.txt', 'a')),
                 TensorboardLogger(tb_log_dir=f'./output/baseline/{args.EXP_NAME}/exp_'+datetime.datetime.now().isoformat()),
                 # WandBLogger(project_name=args.EXP_NAME, config=vars(args),
                 #             dir=f'./output/baseline/{args.EXP_NAME}/wandb_'+datetime.datetime.now().isoformat())
                 ], benchmark=benchmark,)

model: IcarlNet = make_icarl_net(num_classes=benchmark.n_classes)

        model.apply(initialize_icarl_net)

        optim = SGD(
            model.parameters(),
            lr=2.0,
            weight_decay=0.00001,
            momentum=0.9,
        )

        sched = LRSchedulerPlugin(
            MultiStepLR(optim, [49, 63], gamma=1.0 / 5.0)
        )

cl_strategy, initial_exp = checkpoint_plugin.load_checkpoint_if_exists()
model.eval()

results = []
start_time = time.time()
results.append(cl_strategy.eval(benchmark.test_stream,))

**My PyTorch versions:**

torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0

**Comment by AntonioCarta** [comment]
It gets stuck during loading the checkpoint? I noticed some slowdown when saving the checkpoint for some strategies. We are working to improve it.

**Comment by Melika-Ayoughi** [comment]
yes, this is during the loading of the checkpoint. I have 10 experiences and after evaluating the second one, it gets stuck. Does it work if I wait long enough? How can I solve this in my code?

**Comment by AntonioCarta** [comment]
The problem is that the serialization for some attributes is slow. Fortunately, you don't need to store them.

I'm still testing the changes. You can try with this alternative code that allows you to exclude attribute from the serialization:

```
import os.path
import sys
import time
from copy import copy

import dill
import torch

from avalanche.training.determinism.rng_manager import RNGManager


def maybe_load_checkpoint(strategy, fname, map_location=None):
    if not os.path.exists(fname):
        return None, 0

    ckp = torch.load(fname, pickle_module=dill,
                     map_location=map_location)

    print(ckp)
    strategy.__dict__.update(ckp['strategy'].__dict__)
    exp_counter = ckp['exp_counter']
    return strategy, exp_counter


def save_checkpoint(strategy, fname, exclude=None):
    if exclude is None:
        exclude = []
    ended_experience_counter = strategy.clock.train_exp_counter

    strategy = copy(strategy)
    for attr in exclude:
        delattr(strategy, attr)

    checkpoint_data = {
        'strategy': strategy,
        'rng_manager': RNGManager,
        'exp_counter': ended_experience_counter
    }

    print('Saving checkpoint...')
    start_time = time.time()
    # torch.save(checkpoint_data, fname, pickle_module=dill)
    try:
        torch.save(checkpoint_data, fname)
    except Exception as e:
        print('Error saving checkpoint')
        print(e)
        the_type, the_value, the_traceback = sys.exc_info()
        print(the_type)
        print(the_value)
        print(the_traceback)
    else:
        end_time = time.time()
        print('Checkpoint duration:', end_time - start_time)
        print('Checkpoint', ended_experience_counter, 'saved!')
```

here is a list of attributes that you can safely remove. Use it in the `exclude` parameters of `save_checkpoint`:
```
    excluded_ckp_attributes = [
        # these attributes do not have state. Do not save.
        'optimizer',
        'experience',
        'adapted_dataset',
        'dataloader',
        'mbatch',
        'mb_output',
        'current_eval_stream',
        'ood_dataset',
        '_eval_streams'
    ]
```

**Comment by AntonioCarta** [comment]
Fixed by #1338

**Comment by Melika-Ayoughi** [comment]
I get this error after trying your solution:
  ```
File "/gpfs/home2/mayoughi/clvision-challenge-2022/starting_template_instance_classification.py", line 758, in main
    cl_strategy, initial_exp = maybe_load_checkpoint(
  File "/gpfs/home2/mayoughi/clvision-challenge-2022/starting_template_instance_classification.py", line 112, in maybe_load_checkpoint
    ckp = torch.load(fname, pickle_module=dill, map_location=map_location)
  File "/home/mayoughi/.pyenv/versions/clvision_env/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/mayoughi/.pyenv/versions/clvision_env/lib/python3.9/site-packages/torch/serialization.py", line 1045, in _load
    data_file = io.BytesIO(zip_file.get_record(pickle_file))
RuntimeError: PytorchStreamReader failed locating file data.pkl: file not found
```
and I'm excluding the following:
```
exclude=[
                                # these attributes do not have state. Do not save.
                                'optimizer',
                                'experience',
                                'adapted_dataset',
                                'dataloader',
                                'mbatch',
                                'mb_output',
                                'current_eval_stream',
                                # 'ood_dataset',
                                '_eval_streams'
                            ])
```

**Comment by Melika-Ayoughi** [comment]
The evaluation still freezes after experience 2 for ICaRL. Shall I exclude more attributes? I made the following changes according to your implementation:
```
def maybe_load_checkpoint(strategy, fname, map_location=None):
    if not os.path.exists(fname):
        return None, 0

    ckp = torch.load(fname, pickle_module=dill, map_location=map_location)

    print(ckp)
    strategy.__dict__.update(ckp['strategy'].__dict__)
    exp_counter = ckp['exp_counter']
    return strategy, exp_counter


def save_checkpoint(strategy, fname, exclude=None):
    if exclude is None:
        exclude = []
    ended_experience_counter = strategy.clock.train_exp_counter

    strategy = copy(strategy)
    for attr in exclude:
        delattr(strategy, attr)

    checkpoint_data = {
        'strategy': strategy,
        'rng_manager': RNGManager,
        'exp_counter': ended_experience_counter
    }

    print('Saving checkpoint...')
    start_time = time.time()
    try:
        torch.save(checkpoint_data, fname, pickle_module=dill)
    except Exception as e:
        print('Error saving checkpoint')
        print(e)
        the_type, the_value, the_traceback = sys.exc_info()
        print(the_type)
        print(the_value)
        print(the_traceback)
    else:
        end_time = time.time()
        print('Checkpoint duration:', end_time - start_time)
        print('Checkpoint', ended_experience_counter, 'saved!')

cl_strategy = ICaRL(
            model,
            classifier,
            optim,
            memory_size=args.memory_size, #2000,
            buffer_transform=transforms.Compose([augmentation]), #transform applied on buffer elements already modified by test_transform
            device=device,
            train_mb_size=args.batch_size,
            fixed_memory=True,
            train_epochs=args.train_epochs,
            plugins=plugins + [sched],
            evaluator=evaluator,
            # eval_every=0,
        )        
 if args.eval:       
  cl_strategy, initial_exp = maybe_load_checkpoint(
                  cl_strategy, f'../output/clvision-challenge-2022/checkpoints/{args.EXP_NAME}/checkpoint.pkl')
              model.eval()     
  print("Computing accuracy on the complete test set")
          results.append(cl_strategy.eval(benchmark.test_stream, ))
else:
for i, experience in enumerate(benchmark.train_stream):
  cl_strategy.train(
                      experience,
                      **data_loader_arguments)
  save_checkpoint(cl_strategy,
                              f'../output/clvision-challenge-2022/checkpoints/{args.EXP_NAME}/checkpoint.pkl',
                              exclude=[
                                  # these attributes do not have state. Do not save.
                                  'optimizer',
                                  'experience',
                                  'adapted_dataset',
                                  'dataloader',
                                  'mbatch',
                                  'mb_output',
                                  'current_eval_stream',
                                  '_eval_streams'
                              ])

```

**Comment by AntonioCarta** [comment]
It's working on my side on the master branch with `torch==2.0`

Here is the code I'm using. It's loading the checkpoint after every experience to check that the serialization is working:
```
from torch.optim import SGD

from avalanche.benchmarks import SplitCIFAR10
from avalanche.models import make_icarl_net
from avalanche.training import Naive
from avalanche.training.checkpoint import maybe_load_checkpoint, save_checkpoint

device = "cuda"
benchmark = SplitCIFAR10(5)

model = make_icarl_net(num_classes=benchmark.n_classes)
optim = SGD(
    model.parameters(),
    lr=2.0,
    weight_decay=0.00001,
    momentum=0.9,
)

cl_strategy = Naive(model, optim, train_mb_size=128)


for exp in benchmark.train_stream:
    cl_strategy, initial_exp = maybe_load_checkpoint(cl_strategy, "./checkpoint.pkl")
    cl_strategy.train(exp)
    save_checkpoint(cl_strategy, "./checkpoint.pkl")

```
